export const resources = [
  {
    key: 'etudiants',
    title: 'Étudiants',
    singular: 'étudiant',
    endpoint: 'etudiants.php',
    path: '/etudiants',
    icon: '🎓',
    accent: '#7c3aed',
    description: 'Profils étudiants, région, niveau, crédits et résultat final.',
    primaryKey: ['code_module', 'code_session', 'id_etudiant'],
    searchable: ['id_etudiant', 'code_module', 'code_session', 'region', 'niveau_education', 'resultat_final'],
    fields: [
      { name: 'code_module', label: 'Module', type: 'text', required: true },
      { name: 'code_session', label: 'Session', type: 'text', required: true },
      { name: 'id_etudiant', label: 'ID étudiant', type: 'number', required: true },
      { name: 'genre', label: 'Genre', type: 'select', options: ['', 'M', 'F'] },
      { name: 'region', label: 'Région', type: 'text' },
      { name: 'niveau_education', label: 'Niveau éducation', type: 'text' },
      { name: 'tranche_imd', label: 'Tranche IMD', type: 'text' },
      { name: 'tranche_age', label: 'Tranche âge', type: 'text' },
      { name: 'nb_tentatives_precedentes', label: 'Tentatives précédentes', type: 'number' },
      { name: 'credits_etudies', label: 'Crédits étudiés', type: 'number' },
      { name: 'handicap', label: 'Handicap', type: 'select', options: ['', 'N', 'Y'] },
      { name: 'resultat_final', label: 'Résultat final', type: 'select', options: ['', 'Distinction', 'Pass', 'Fail', 'Withdrawn'] },
    ],
    tableColumns: ['id_etudiant', 'code_module', 'code_session', 'genre', 'region', 'credits_etudies', 'resultat_final'],
  },
  {
    key: 'modules',
    title: 'Modules',
    singular: 'module',
    endpoint: 'modules.php',
    path: '/modules',
    icon: '📚',
    accent: '#2563eb',
    description: 'Catalogue des modules et durées de sessions.',
    primaryKey: ['code_module', 'code_session'],
    searchable: ['code_module', 'code_session', 'duree'],
    fields: [
      { name: 'code_module', label: 'Code module', type: 'text', required: true },
      { name: 'code_session', label: 'Code session', type: 'text', required: true },
      { name: 'duree', label: 'Durée', type: 'number', required: true },
    ],
    tableColumns: ['code_module', 'code_session', 'duree'],
  },
  {
    key: 'evaluations',
    title: 'Évaluations',
    singular: 'évaluation',
    endpoint: 'evaluations.php',
    path: '/evaluations',
    icon: '📝',
    accent: '#d97706',
    description: 'Évaluations, types, dates pédagogiques et poids.',
    primaryKey: ['id_evaluation'],
    searchable: ['id_evaluation', 'code_module', 'code_session', 'type_evaluation'],
    fields: [
      { name: 'id_evaluation', label: 'ID évaluation', type: 'number', required: true },
      { name: 'code_module', label: 'Module', type: 'text', required: true },
      { name: 'code_session', label: 'Session', type: 'text', required: true },
      { name: 'type_evaluation', label: 'Type', type: 'select', required: true, options: ['Devoir', 'Examen', 'TP', 'Quiz', 'Projet'] },
      { name: 'date_evaluation', label: 'Date évaluation', type: 'number' },
      { name: 'poids', label: 'Poids', type: 'number', step: '0.01', required: true },
    ],
    tableColumns: ['id_evaluation', 'code_module', 'code_session', 'type_evaluation', 'date_evaluation', 'poids'],
  },
  {
    key: 'inscriptions',
    title: 'Inscriptions',
    singular: 'inscription',
    endpoint: 'inscriptions.php',
    path: '/inscriptions',
    icon: '✅',
    accent: '#059669',
    description: 'Dates d’inscription et de désinscription des étudiants.',
    primaryKey: ['code_module', 'code_session', 'id_etudiant'],
    searchable: ['id_etudiant', 'code_module', 'code_session'],
    fields: [
      { name: 'code_module', label: 'Module', type: 'text', required: true },
      { name: 'code_session', label: 'Session', type: 'text', required: true },
      { name: 'id_etudiant', label: 'ID étudiant', type: 'number', required: true },
      { name: 'date_inscription', label: 'Date inscription', type: 'number' },
      { name: 'date_desinscription', label: 'Date désinscription', type: 'number' },
    ],
    tableColumns: ['id_etudiant', 'code_module', 'code_session', 'date_inscription', 'date_desinscription'],
  },
  {
    key: 'ressources',
    title: 'Ressources VLE',
    singular: 'ressource',
    endpoint: 'ressources_vle.php',
    path: '/ressources',
    icon: '🔗',
    accent: '#4f46e5',
    description: 'Ressources pédagogiques, activités VLE et semaines associées.',
    primaryKey: ['code_module', 'code_session', 'id_ressource'],
    searchable: ['id_ressource', 'code_module', 'code_session', 'type_activite'],
    fields: [
      { name: 'id_ressource', label: 'ID ressource', type: 'number', required: true },
      { name: 'code_module', label: 'Module', type: 'text', required: true },
      { name: 'code_session', label: 'Session', type: 'text', required: true },
      { name: 'type_activite', label: 'Type activité', type: 'select', required: true, options: ['homepage', 'forumng', 'resource', 'quiz', 'oucollaborate', 'url', 'subpage'] },
      { name: 'semaine_debut', label: 'Semaine début', type: 'number' },
      { name: 'semaine_fin', label: 'Semaine fin', type: 'number' },
    ],
    tableColumns: ['id_ressource', 'code_module', 'code_session', 'type_activite', 'semaine_debut', 'semaine_fin'],
  },
  {
    key: 'resultats',
    title: 'Résultats évaluations',
    singular: 'résultat',
    endpoint: 'resultats_evaluations.php',
    path: '/resultats',
    icon: '📊',
    accent: '#db2777',
    description: 'Notes, conservation et soumissions des évaluations.',
    primaryKey: ['id_evaluation', 'id_etudiant'],
    searchable: ['id_evaluation', 'id_etudiant', 'code_module', 'code_session', 'note'],
    fields: [
      { name: 'code_module', label: 'Module', type: 'text', required: true },
      { name: 'code_session', label: 'Session', type: 'text', required: true },
      { name: 'id_evaluation', label: 'ID évaluation', type: 'number', required: true },
      { name: 'id_etudiant', label: 'ID étudiant', type: 'number', required: true },
      { name: 'date_soumission', label: 'Date soumission', type: 'number' },
      { name: 'est_conserve', label: 'Conservé', type: 'select', options: ['', '1', '0'] },
      { name: 'note', label: 'Note', type: 'number', step: '0.01' },
    ],
    tableColumns: ['id_evaluation', 'id_etudiant', 'code_module', 'code_session', 'date_soumission', 'est_conserve', 'note'],
  },
  {
    key: 'interactions',
    title: 'Interactions VLE',
    singular: 'interaction',
    endpoint: 'interactions_vle.php',
    path: '/interactions',
    icon: '🖱️',
    accent: '#ea580c',
    description: 'Interactions étudiants-ressources et nombre de clics.',
    primaryKey: ['id_interaction'],
    searchable: ['id_interaction', 'id_etudiant', 'id_ressource', 'code_module', 'code_session'],
    fields: [
      { name: 'id_interaction', label: 'ID interaction', type: 'number', auto: true },
      { name: 'code_module', label: 'Module', type: 'text', required: true },
      { name: 'code_session', label: 'Session', type: 'text', required: true },
      { name: 'id_etudiant', label: 'ID étudiant', type: 'number', required: true },
      { name: 'id_ressource', label: 'ID ressource', type: 'number', required: true },
      { name: 'date_interaction', label: 'Date interaction', type: 'number', required: true },
      { name: 'nb_clics', label: 'Nombre de clics', type: 'number', required: true },
    ],
    tableColumns: ['id_interaction', 'id_etudiant', 'id_ressource', 'code_module', 'code_session', 'date_interaction', 'nb_clics'],
  },
];

export const resourceByKey = Object.fromEntries(resources.map((resource) => [resource.key, resource]));
export const resourceByPath = Object.fromEntries(resources.map((resource) => [resource.path, resource]));
